# This adds the actual test suite to the base image, so that it can be used to
# test CMP implementations.
# By default it attempts to use the locally stored image, but you can also rely
# on an external image registry if you specify another base when building:
# `docker build --build-arg BASE_IMAGE=ghcr.io/${GITHUB_REPOSITORY_OWNER}/cmp-test-base:latest -f data/dockerfiles/Dockerfile.tests .`
# To experiment locally, build it with:
# `docker build -t cmptest-tests -f data/dockerfiles/Dockerfile.tests .`
# Run it with `docker run --rm -it cmptest-tests`

ARG BASE_IMAGE=cmptest-base:latest
FROM ${BASE_IMAGE}

WORKDIR /app

COPY . /app

# Run the entry point script, it takes care of command line argument parsing and
# displaying documentation.
ENTRYPOINT ["scripts/docker_entrypoint.py"]
CMD ["--smoke"]
